<a href="https://colab.research.google.com/github/jmn-cdcc185d6y2746/analisa-data/blob/main/notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Proyek Analisis Data: Bike Sharing
- **Nama:** Jose Morinho Ngadio
- **Email:** cdcc185d6y2746@student.devacademy.id
- **ID Dicoding:** CDCC185D6Y2746

## Menentukan Pertanyaan Bisnis

- **Pertanyaan 1:** "Apakah ada pertumbuhan jumlah penyewa sepeda dari tahun 2011 sampai 2012 berdasarkan musim-musim?"
  - Specific: Fokus pada pertumbuhan jumlah penyewa dari musim ke musim
  - Measurable: Akan mengukur pertumbuhan dari jumlah penyewa sepeda
  - Action-Oriented: Mendapatkan jawaban untuk pertanyaan ini akan membantu perusahaan untuk mempertimbangkan ekspansi di daerah baru
  - Relevant: Dapat memberikan insight sebagai pertimbangan ekspansi
  - Time-bound: Membatasi waktu dari tahun 2011 sampai 2012 sesuai ketersediaan data
- **Pertanyaan 2:** "Pada jam berapa demand penyewaan sepeda mencapai titik puncakanya?"
  - Specific: Fokus mencari waktu dimana penyewaan sepeda memuncak
  - Measurable: Akan menggunakan hour.csv untuk menjawab pertanyaan
  - Action-Oriented: Perusahaan dapat menjadwalkan restock sepeda secara strategis untuk meningkatkan penyewaan
  - Relevant: Dapat memberikan insight terkait kapan sepeda harus direstock, khususnya di puncak aktifitas
  - Time-bound: Memanfaatkan tanggal dan waktu yang tersedia dalam .csv (tahun 2011 sampai 2012)

## Import Semua Packages/Library yang Digunakan

In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

## Data Wrangling

### Gathering Data

#### Load df ...

In [7]:
df_day = pd.read_csv('https://raw.githubusercontent.com/jmn-cdcc185d6y2746/analisa-data/main/data/day.csv')
df_day

,instant,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,1,2011-01-01,1,0,1,0,6,0,2,0.344167,0.363625,0.805833,0.160446,331,654,985
1,2,2011-01-02,1,0,1,0,0,0,2,0.363478,0.353739,0.696087,0.248539,131,670,801
2,3,2011-01-03,1,0,1,0,1,1,1,0.196364,0.189405,0.437273,0.248309,120,1229,1349
3,4,2011-01-04,1,0,1,0,2,1,1,0.200000,0.212122,0.590435,0.160296,108,1454,1562
4,5,2011-01-05,1,0,1,0,3,1,1,0.226957,0.229270,0.436957,0.186900,82,1518,1600
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
726,727,2012-12-27,1,1,12,0,4,1,2,0.254167,0.226642,0.652917,0.350133,247,1867,2114
727,728,2012-12-28,1,1,12,0,5,1,2,0.253333,0.255046,0.590000,0.155471,644,2451,3095
728,729,2012-12-29,1,1,12,0,6,0,2,0.253333,0.242400,0.752917,0.124383,159,1182,1341
729,730,2012-12-30,1,1,12,0,0,0,1,0.255833,0.231700,0.483333,0.350754,364,1432,1796
730,731,2012-12-31,1,1,12,0,1,1,2,0.215833,0.223487,0.577500,0.154846,439,2290,2729

In [8]:
df_hour = pd.read_csv('https://raw.githubusercontent.com/jmn-cdcc185d6y2746/analisa-data/main/data/hour.csv')
df_hour

,instant,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,1,2011-01-01,1,0,1,0,0,6,0,1,0.24,0.2879,0.81,0.0000,3,13,16
1,2,2011-01-01,1,0,1,1,0,6,0,1,0.22,0.2727,0.80,0.0000,8,32,40
2,3,2011-01-01,1,0,1,2,0,6,0,1,0.22,0.2727,0.80,0.0000,5,27,32
3,4,2011-01-01,1,0,1,3,0,6,0,1,0.24,0.2879,0.75,0.0000,3,10,13
4,5,2011-01-01,1,0,1,4,0,6,0,1,0.24,0.2879,0.75,0.0000,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17374,17375,2012-12-31,1,1,12,19,0,1,1,2,0.26,0.2576,0.60,0.1642,11,108,119
17375,17376,2012-12-31,1,1,12,20,0,1,1,2,0.26,0.2576,0.60,0.1642,8,81,89
17376,17377,2012-12-31,1,1,12,21,0,1,1,1,0.26,0.2576,0.60,0.1642,7,83,90
17377,17378,2012-12-31,1,1,12,22,0,1,1,1,0.26,0.2727,0.56,0.1343,13,48,61
17378,17379,2012-12-31,1,1,12,23,0,1,1,1,0.26,0.2727,0.65,0.1343,12,37,49

**Insight:** (Opsional)
- df_day menunjukkan penggunaan bike sharing berdasarkan hari sedangkan df_hour menunjukkan penggunaan bike sharing berdasarkan jam.
- Keduan data memiliki kolom weathersit, temp, atemp, dan hum yang dapat membantu menganalisa terkait musim.

### Assessing Data

#### Identifying df_day

In [ ]:
df_day.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 731 entries, 0 to 730
Data columns (total 16 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   instant     731 non-null    int64
 1   dteday      731 non-null    object
 2   season      731 non-null    int64
 3   yr          731 non-null    int64
 4   mnth        731 non-null    int64
 5   holiday     731 non-null    int64
 6   weekday     731 non-null    int64
 7   workingday  731 non-null    int64
 8   weathersit  731 non-null    int64
 9   temp        731 non-null    float64
 10  atemp       731 non-null    float64
 11  hum         731 non-null    float64
 12  windspeed   731 non-null    float64
 13  casual      731 non-null    int64
 14  registered  731 non-null    int64
 15  cnt         731 non-null    int64
dtypes: float64(4), int64(11), object(1)
memory usage: 91.5+ KB

In [ ]:
df_day.isna().sum()

instant       0
dteday        0
season        0
yr            0
mnth          0
holiday       0
weekday       0
workingday    0
weathersit    0
temp          0
atemp         0
hum           0
windspeed     0
casual        0
registered    0
cnt           0
dtype: int64

In [ ]:
df_day.duplicated().sum()

np.int64(0)

In [ ]:
df_day.describe()

,instant,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
count,731.000000,731.000000,731.000000,731.000000,731.000000,731.000000,731.000000,731.000000,731.000000,731.000000,731.000000,731.000000,731.000000,731.000000,731.000000
mean,366.000000,2.496580,0.500684,6.519836,0.028728,2.997264,0.683995,1.395349,0.495385,0.474354,0.627894,0.190486,848.176471,3656.172367,4504.348837
std,211.165812,1.110807,0.500342,3.451913,0.167155,2.004787,0.465233,0.544894,0.183051,0.162961,0.142429,0.077498,686.622488,1560.256377,1937.211452
min,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.059130,0.079070,0.000000,0.022392,2.000000,20.000000,22.000000
25%,183.500000,2.000000,0.000000,4.000000,0.000000,1.000000,0.000000,1.000000,0.337083,0.337842,0.520000,0.134950,315.500000,2497.000000,3152.000000
50%,366.000000,3.000000,1.000000,7.000000,0.000000,3.000000,1.000000,1.000000,0.498333,0.486733,0.626667,0.180975,713.000000,3662.000000,4548.000000
75%,548.500000,3.000000,1.000000,10.000000,0.000000,5.000000,1.000000,2.000000,0.655417,0.608602,0.730209,0.233214,1096.000000,4776.500000,5956.000000
max,731.000000,4.000000,1.000000,12.000000,1.000000,6.000000,1.000000,3.000000,0.861667,0.840896,0.972500,0.507463,3410.000000,6946.000000,8714.000000

**Steps to Take:**
Data sudah bersih. Namun, untuk kemudahan membaca analisa, data pada kolom tahun dan season akan diubah menjadi format string

#### Identifying df_day

In [12]:
df_hour.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17379 entries, 0 to 17378
Data columns (total 17 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   instant     17379 non-null  int64
 1   dteday      17379 non-null  object
 2   season      17379 non-null  int64
 3   yr          17379 non-null  int64
 4   mnth        17379 non-null  int64
 5   hr          17379 non-null  int64
 6   holiday     17379 non-null  int64
 7   weekday     17379 non-null  int64
 8   workingday  17379 non-null  int64
 9   weathersit  17379 non-null  int64
 10  temp        17379 non-null  float64
 11  atemp       17379 non-null  float64
 12  hum         17379 non-null  float64
 13  windspeed   17379 non-null  float64
 14  casual      17379 non-null  int64
 15  registered  17379 non-null  int64
 16  cnt         17379 non-null  int64
dtypes: float64(4), int64(12), object(1)
memory usage: 2.3+ MB

In [11]:
df_hour.isna().sum()

instant       0
dteday        0
season        0
yr            0
mnth          0
hr            0
holiday       0
weekday       0
workingday    0
weathersit    0
temp          0
atemp         0
hum           0
windspeed     0
casual        0
registered    0
cnt           0
dtype: int64

In [10]:
df_hour.duplicated().sum()

np.int64(0)

In [9]:
df_hour.describe()

,instant,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
count,17379.0000,17379.000000,17379.000000,17379.000000,17379.000000,17379.000000,17379.000000,17379.000000,17379.000000,17379.000000,17379.000000,17379.000000,17379.000000,17379.000000,17379.000000,17379.000000
mean,8690.0000,2.501640,0.502561,6.537775,11.546752,0.028770,3.003683,0.682721,1.425283,0.496987,0.475775,0.627229,0.190098,35.676218,153.786869,189.463088
std,5017.0295,1.106918,0.500008,3.438776,6.914405,0.167165,2.005771,0.465431,0.639357,0.192556,0.171850,0.192930,0.122340,49.305030,151.357286,181.387599
min,1.0000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.020000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
25%,4345.5000,2.000000,0.000000,4.000000,6.000000,0.000000,1.000000,0.000000,1.000000,0.340000,0.333300,0.480000,0.104500,4.000000,34.000000,40.000000
50%,8690.0000,3.000000,1.000000,7.000000,12.000000,0.000000,3.000000,1.000000,1.000000,0.500000,0.484800,0.630000,0.194000,17.000000,115.000000,142.000000
75%,13034.5000,3.000000,1.000000,10.000000,18.000000,0.000000,5.000000,1.000000,2.000000,0.660000,0.621200,0.780000,0.253700,48.000000,220.000000,281.000000
max,17379.0000,4.000000,1.000000,12.000000,23.000000,1.000000,6.000000,1.000000,4.000000,1.000000,1.000000,1.000000,0.850700,367.000000,886.000000,977.000000

**Steps to Take:**
Seperti df_day, data sudah bersih. Namun, untuk kemudahan membaca analisa, data pada kolom tahun dan season akan diubah menjadi format string

**Insight:** (Opsional)
- Dalam melakukan assesment data, kita harus melihat dari konsistensi data, adanya duplikat atau tidak serta adakah data kosong atau tidak.
- Tidak semua dataset datang dalam bentuk bersih, beberapa datang dalam kondisi belum diolah. Sebaliknya juga bisa terjadi. Pada kasus ini, data kebetulan sudah bersih sehingga tidak butuh diubah kecuali ingin ada penyesuaian.

### Cleaning Data

#### Fixing df_day

In [13]:
df_day['yr'] = df_day['yr'].map({0: '2011', 1: '2012'})
df_day['season'] = df_day['season'].map({1: 'Spring', 2: 'Summer', 3: 'Fall', 4: 'Winter'})

In [15]:
df_day.head()

,instant,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,1,2011-01-01,Spring,2011,1,0,6,0,2,0.344167,0.363625,0.805833,0.160446,331,654,985
1,2,2011-01-02,Spring,2011,1,0,0,0,2,0.363478,0.353739,0.696087,0.248539,131,670,801
2,3,2011-01-03,Spring,2011,1,0,1,1,1,0.196364,0.189405,0.437273,0.248309,120,1229,1349
3,4,2011-01-04,Spring,2011,1,0,2,1,1,0.200000,0.212122,0.590435,0.160296,108,1454,1562
4,5,2011-01-05,Spring,2011,1,0,3,1,1,0.226957,0.229270,0.436957,0.186900,82,1518,1600

#### Fixing df_hour

In [16]:
df_hour['yr'] = df_hour['yr'].map({0: '2011', 1: '2012'})
df_hour['season'] = df_hour['season'].map({1: 'Spring', 2: 'Summer', 3: 'Fall', 4: 'Winter'})

In [17]:
df_hour.head()

,instant,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,1,2011-01-01,Spring,2011,1,0,0,6,0,1,0.24,0.2879,0.81,0.0,3,13,16
1,2,2011-01-01,Spring,2011,1,1,0,6,0,1,0.22,0.2727,0.80,0.0,8,32,40
2,3,2011-01-01,Spring,2011,1,2,0,6,0,1,0.22,0.2727,0.80,0.0,5,27,32
3,4,2011-01-01,Spring,2011,1,3,0,6,0,1,0.24,0.2879,0.75,0.0,3,10,13
4,5,2011-01-01,Spring,2011,1,4,0,6,0,1,0.24,0.2879,0.75,0.0,0,1,1

**Insight:** (Opsional)
- Membersihkan data merupakan tahap krusial untuk memastikan kelancaran dalam pengolahan data serta mempermudah interpretasi data sebagai suatu insight.
- Pada cleaning data, saya hanya melakukan perubahan tipe data season dan yr dari numerik menjadi string untuk mempermudah pembacaan.

## Exploratory Data Analysis (EDA)

### Explore df_day

In [18]:
df_day.sample(5)

,instant,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
378,379,2012-01-14,Spring,2012,1,0,6,0,1,0.180000,0.183087,0.457500,0.187183,333,2160,2493
238,239,2011-08-27,Fall,2011,8,0,6,0,2,0.680000,0.635556,0.850000,0.375617,226,889,1115
260,261,2011-09-18,Fall,2011,9,0,0,0,1,0.507500,0.490537,0.695000,0.178483,1353,2921,4274
394,395,2012-01-30,Spring,2012,1,0,1,1,1,0.269167,0.262625,0.400833,0.215792,126,3498,3624
571,572,2012-07-25,Fall,2012,7,0,3,1,1,0.724167,0.654054,0.450000,0.164800,1383,6790,8173

In [19]:
df_day.describe(include="all")

,instant,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
count,731.000000,731,731,731,731.000000,731.000000,731.000000,731.000000,731.000000,731.000000,731.000000,731.000000,731.000000,731.000000,731.000000,731.000000
unique,NaN,731,4,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,2012-12-31,Fall,2012,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,1,188,366,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,366.000000,NaN,NaN,NaN,6.519836,0.028728,2.997264,0.683995,1.395349,0.495385,0.474354,0.627894,0.190486,848.176471,3656.172367,4504.348837
std,211.165812,NaN,NaN,NaN,3.451913,0.167155,2.004787,0.465233,0.544894,0.183051,0.162961,0.142429,0.077498,686.622488,1560.256377,1937.211452
min,1.000000,NaN,NaN,NaN,1.000000,0.000000,0.000000,0.000000,1.000000,0.059130,0.079070,0.000000,0.022392,2.000000,20.000000,22.000000
25%,183.500000,NaN,NaN,NaN,4.000000,0.000000,1.000000,0.000000,1.000000,0.337083,0.337842,0.520000,0.134950,315.500000,2497.000000,3152.000000
50%,366.000000,NaN,NaN,NaN,7.000000,0.000000,3.000000,1.000000,1.000000,0.498333,0.486733,0.626667,0.180975,713.000000,3662.000000,4548.000000
75%,548.500000,NaN,NaN,NaN,10.000000,0.000000,5.000000,1.000000,2.000000,0.655417,0.608602,0.730209,0.233214,1096.000000,4776.500000,5956.000000
max,731.000000,NaN,NaN,NaN,12.000000,1.000000,6.000000,1.000000,3.000000,0.861667,0.840896,0.972500,0.507463,3410.000000,6946.000000,8714.000000

In [23]:
pertumbuhan = df_day.groupby(by=["yr", "season"]).agg({
    "cnt": "sum"
}).reset_index()

display(pertumbuhan)

     yr  season     cnt
0  2011    Fall  419650
1  2011  Spring  150000
2  2011  Summer  347316
3  2011  Winter  326137
4  2012    Fall  641479
5  2012  Spring  321348
6  2012  Summer  571273
7  2012  Winter  515476

### Explore df_hour

In [24]:
df_hour.sample(15)

,instant,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
7050,7051,2011-10-26,Winter,2011,10,9,0,3,1,2,0.48,0.4697,0.63,0.2239,14,226,240
13436,13437,2012-07-19,Fall,2012,7,1,0,4,1,1,0.74,0.6970,0.66,0.0896,6,19,25
13415,13416,2012-07-18,Fall,2012,7,4,0,3,1,1,0.72,0.6818,0.70,0.1343,0,6,6
9463,9464,2012-02-04,Spring,2012,2,5,0,6,0,1,0.24,0.2576,0.81,0.0896,1,3,4
2242,2243,2011-04-08,Summer,2011,4,7,0,5,1,3,0.34,0.3333,0.87,0.1642,4,109,113
2279,2280,2011-04-09,Summer,2011,4,20,0,6,0,2,0.38,0.3939,0.87,0.1642,19,74,93
6691,6692,2011-10-11,Winter,2011,10,9,0,2,1,2,0.60,0.5909,0.69,0.0000,40,195,235
7934,7935,2011-12-02,Winter,2011,12,6,0,5,1,1,0.22,0.2727,0.80,0.0000,3,84,87
12039,12040,2012-05-21,Summer,2012,5,20,0,1,1,1,0.64,0.6061,0.69,0.1343,44,292,336
9136,9137,2012-01-21,Spring,2012,1,14,0,6,0,3,0.20,0.1970,0.80,0.1940,6,89,95
4701,4702,2011-07-19,Fall,2011,7,19,0,2,1,1,0.76,0.7424,0.75,0.1940,54,334,388
8803,8804,2012-01-07,Spring,2012,1,15,0,6,0,1,0.58,0.5455,0.37,0.2985,132,317,449
10349,10350,2012-03-12,Spring,2012,3,8,0,1,1,1,0.34,0.3333,0.61,0.1343,17,547,564
10020,10021,2012-02-27,Spring,2012,2,13,0,1,1,1,0.40,0.4091,0.43,0.2836,23,159,182
8901,8902,2012-01-11,Spring,2012,1,18,0,3,1,3,0.34,0.3333,0.87,0.1940,2,96,98

In [25]:
df_hour.describe(include="all")

,instant,dteday,season,yr,mnth,hr,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
count,17379.0000,17379,17379,17379,17379.000000,17379.000000,17379.000000,17379.000000,17379.000000,17379.000000,17379.000000,17379.000000,17379.000000,17379.000000,17379.000000,17379.000000,17379.000000
unique,NaN,731,4,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,2012-12-31,Fall,2012,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,24,4496,8734,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,8690.0000,NaN,NaN,NaN,6.537775,11.546752,0.028770,3.003683,0.682721,1.425283,0.496987,0.475775,0.627229,0.190098,35.676218,153.786869,189.463088
std,5017.0295,NaN,NaN,NaN,3.438776,6.914405,0.167165,2.005771,0.465431,0.639357,0.192556,0.171850,0.192930,0.122340,49.305030,151.357286,181.387599
min,1.0000,NaN,NaN,NaN,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.020000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
25%,4345.5000,NaN,NaN,NaN,4.000000,6.000000,0.000000,1.000000,0.000000,1.000000,0.340000,0.333300,0.480000,0.104500,4.000000,34.000000,40.000000
50%,8690.0000,NaN,NaN,NaN,7.000000,12.000000,0.000000,3.000000,1.000000,1.000000,0.500000,0.484800,0.630000,0.194000,17.000000,115.000000,142.000000
75%,13034.5000,NaN,NaN,NaN,10.000000,18.000000,0.000000,5.000000,1.000000,2.000000,0.660000,0.621200,0.780000,0.253700,48.000000,220.000000,281.000000
max,17379.0000,NaN,NaN,NaN,12.000000,23.000000,1.000000,6.000000,1.000000,4.000000,1.000000,1.000000,1.000000,0.850700,367.000000,886.000000,977.000000

In [22]:
permintaan = df_hour.groupby(by='hr').agg({
    "cnt": "mean"
}).reset_index().sort_values(by='cnt', ascending=False)

display(permintaan)

    hr         cnt
17  17  461.452055
18  18  425.510989
8    8  359.011004
16  16  311.983562
19  19  311.523352
13  13  253.661180
12  12  253.315934
15  15  251.233196
14  14  240.949246
20  20  226.030220
9    9  219.309491
7    7  212.064649
11  11  208.143054
10  10  173.668501
21  21  172.314560
22  22  131.335165
23  23   87.831044
6    6   76.044138
0    0   53.898072
1    1   33.375691
2    2   22.869930
5    5   19.889819
3    3   11.727403
4    4    6.352941

**Insight:** (Opsional)
- Exploratory Data Analysis digunakan untuk menjelajahi data agar kita bisa menemukan jawaban kita. Dalam penjelajahan ini, data tidak hanya sekedar dibaca, namun juga dimanipulasi baik digabungkan atau diurutkan
- Pada bagian ini, saya memanipulasi setiap data dan mengurutkannya. Untuk df_day, saya mengurutkan lalu menjumlahkan kolom count untuk mendapatkan total dari cnt (jumlah) pada tahun dan musim itu. Untuk df_hour, saya mengurutkan lalu merata-ratakan kolom count untuk mendapatkan rata-rata pengguna berdasarkan jam tertentu, lalu mengurutkannya berdasarkan cnt terbanyak

## Visualization & Explanatory Analysis

### Pertanyaan 1: Apakah ada pertumbuhan jumlah penyewa sepeda dari tahun 2011 sampai 2012 berdasarkan musim-musim?

### Pertanyaan 2: Pada jam berapa demand penyewaan sepeda mencapai titik puncakanya?

**Insight:** (Opsional)
- xxx
- xxx

## Analisis Lanjutan (Opsional)

## Conclusion & Recommendation

- **Conclusion pertanyaan 1:** xxx
- **Conclusion pertanyaan 2:** xxx
- ...

**Rekomendasi Action Item:**
- xxx
- xxx